//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreditsEntities : DbContext
    {
        public CreditsEntities()
            : base("name=CreditsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Debtor> Debtors { get; set; }
        public virtual DbSet<InformationAboutLoan> InformationAboutLoans { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<RealEstateCategory> RealEstateCategories { get; set; }
        public virtual DbSet<RealEstateObject> RealEstateObjects { get; set; }
        public virtual DbSet<RealEstateType> RealEstateTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
