//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int ID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> DebtorID { get; set; }
        public Nullable<int> InformationAboutLoansID { get; set; }
        public Nullable<int> RealEstateObjectsID { get; set; }
        public string AdditionalConditions { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsDecline { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Debtor Debtor { get; set; }
        public virtual InformationAboutLoan InformationAboutLoan { get; set; }
        public virtual RealEstateObject RealEstateObject { get; set; }
    }
}
