//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstateObject()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RealEstateTypeID { get; set; }
        public Nullable<int> RealEstateCategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Paid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual RealEstateCategory RealEstateCategory { get; set; }
        public virtual RealEstateType RealEstateType { get; set; }
    }
}
